CREATE TABLE "SESION" (
	"ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
	"fechaInicio" DATETIME);
CREATE TABLE "PROYECTO" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nombre" VARCHAR NOT NULL , "fechaInicio" DATETIME NOT NULL , "fechaTermino" DATETIME, "idSesion" INTEGER, FOREIGN KEY(idSesion) REFERENCES SESION(ID));
CREATE TABLE "ProyPac" ("idProyecto" INTEGER NOT NULL , "idPaciente" INTEGER NOT NULL , PRIMARY KEY ("idProyecto", "idPaciente"),FOREIGN KEY(idProyecto) REFERENCES PROYECTO(ID),FOREIGN KEY(idPaciente) REFERENCES PACIENTES(ID));
CREATE TABLE "PACIENTES" ("RUT" VARCHAR PRIMARY KEY  NOT NULL , "nombre" VARCHAR, "apellido" VARCHAR, "direccion" VARCHAR);
CREATE TABLE "SEÑAL" ("ID" INTEGER PRIMARY KEY  NOT NULL , "fs" INTEGER NOT NULL , "idPaciente" INTEGER, FOREIGN KEY(idPaciente) REFERENCES PACIENTES(ID));
CREATE TABLE "ESTADISTICAS" ("ID" INTEGER NOT NULL , "IDSeñal" INTEGER NOT NULL , PRIMARY KEY ("ID", "IDSeñal"),FOREIGN KEY(IDSEÑAL) REFERENCES SEÑAL(ID));
